title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: castlechoi

url: https://castlechoi.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

gems:
  - index
